name: awesome_bubble
description: A Flutter Plugin to show Messenger Bubble, over all other apps.This plugin shows overlay bubble and notification.
version: 0.0.1+1
homepage: https://github.com/mohamedhaloka/awesome_bubble

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.head.bubble
        pluginClass: BubblePlugin